version: '4'

services:
  webserver:
    image: php:8.3-apache
    container_name: webserver
    ports:
      - 8080:80
    volumes:
      - ${PWD}:/var/www/html/
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    
  composer:
    image: composer:latest
    container_name: composer_installer
    command: ["composer", "install"]
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - mysql